version: '3'
services:
  web:
    build: .
    ports:
      - "9191:80"
  server:
    build: ../SwarmBrowserServer
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
