version: '3'
services:
  web:
    image:  docker.docapost.tech/jdc/recette/swarmbrowser/swarmbrowser:1.0.0
    ports:
      - "9191:80"
  server:
    image:  docker.docapost.tech/jdc/recette/swarmbrowserserver/swarmbrowserserver:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
